### ISSUE TITLE
Incorrect warning: "float can't be used with display:inline"

### ISSUE THREAD

**Issue by necolas** [CSSLint/csslint#16]
`display:inline` will just be ignored when using `float` - unless in IE6, where it is used as a fix for the double-margin bug on floats - so the warning text could be altered to reflect this.

**Comment by jobscaptain** [comment]
same warning  "float can't be used with display:inline"
 .header-widgets-three { display: inline-block; float: left; width: 100%; max-width: 31.3%; padding:30px 0; }
