### ISSUE TITLE
Heading (h1) has already been defined

### ISSUE THREAD

**Issue by stenehall** [CSSLint/csslint#194]
I know there's already discussions about multiple heading declarations but those seemed to be based on different reasoning.

In (at least) html5 it's perfectly ok to have multiple h1s on the same page. In fact, from what I understand having a new h1 in each section is more than ok. Since different sections is just that, different parts of the page it's perfectly viable to style them differently.
Using different sizes, colors and fonts.

So in my opinion the entire rule should be removed. Or at least checked against a different scope.

Just realized I totally missed http://groups.google.com/group/css-lint/browse_thread/thread/dc33aaa950765efb and should probably have posted there instead. However I still think it should be allowed to style different sections headings without getting a warning. Not by stacking sessions but by adding a class/id to the section.

I.e.

&lt;section id=&quot;twitter&quot;&gt;
&lt;h1&gt;Foo&lt;/h1&gt;
...
...
...
&lt;/section&gt;
&lt;section id=&quot;facebook&quot;&gt;
&lt;h1&gt;Bar&lt;/h1&gt;
...
...
...
&lt;/section&gt;

**Comment by bloodbeast234** [comment]
<a href=www.minecraft.net>hello world</a>
