### ISSUE TITLE
Implement .csslintignore (skipping files and/or directories)

### ISSUE THREAD

**Issue by Krinkle** [CSSLint/csslint#330]
When running `csslint` on a repository, it would be useful to be able to run it recursively on the current directory excluding certain files, patterns or directories (such as `node_modules/`, `libs/`, `dest/**/*.css`, ..).

Could probably use something like [minimatch](https://github.com/isaacs/minimatch) (like jshint does for `.jshintignore`).

**Comment by mcandre** [comment]
I'm satisfied with how csslint uses per-user/per-directory `.csslintrc` `--excludes=...` flags to accomplish this feature. Motion to close?

**Comment by frvge** [comment]
Exclusion is possible with in-file comments and per-line annotations. This will be available in the next release.

**Comment by mcandre** [comment]
That helps, but it's not practical as the only option, with large, pre-linted projects.

**Comment by Krinkle** [comment]
Switched to <https://stylelint.io/>.
