### ISSUE TITLE
Support jshint style JSON format for .csslintrc file

### ISSUE THREAD

**Issue by jzaefferer** [CSSLint/csslint#359]
This came up when adding .csslintrc file support to grunt-contrib-csslint: https://github.com/gruntjs/grunt-contrib-csslint/pull/6

Turns out the format the csslint expects is CLI options in a file. It would be great to instead support a format equivalent to what jshint supports in its .jshintrc file, matching what CSSLint also expects when using it programmatically.

As an usage example of the preferred format, here's a commit in jQuery UI where we moved from options to .csslintrc file: https://github.com/jquery/jquery-ui/commit/39a2f465a54d93777781c1a97cb58953a7d6557e

Since csslint is still not on a 1.x.x release, I suggest to change the format instead of trying to support both.

Also related is this ticket for SublimeLinter, to add support for .csslintrc files: https://github.com/SublimeLinter/SublimeLinter/issues/386

If this is acceptable, I'll try to put together a pull request.

/cc @tkellen @scottgonzalez

**Comment by stela5** [comment]
@nschonni Any ETA on the *Next version*?  I'd like to suppress warnings via a .csslintrc file

**Comment by wangxds** [comment]
可以，很棒！
