### ISSUE TITLE
@-moz-document crashes parser

### ISSUE THREAD

**Issue by GREENpoint** [CSSLint/csslint#421]
Unknown rule that crashes parser.

**Comment by mendeza** [comment]
Oh, thank goodness!

**Comment by jawshooah** [comment]
I've submitted a PR to fix this: CSSLint/parser-lib#137.

Hoping for a quick response.

**Comment by steveworkman** [comment]
That PR has been merged, but parser-lib hasn't been released since (or for almost a year)! This is breaking CSSLint completely for me

**Comment by mendeza** [comment]
As the parser is the heart of the project, csslint can be considered abandonware. I'm using [csslint-next](https://www.npmjs.com/package/csslint-next). In my gruntfile (would be the same using npm-scripts) I drop into the shell to use it, like so:
```
cssLintThis: {
  command: './node_modules/csslint-next/cli.js --format=compact --warnings=known-properties path/to/project/**/file.css',
  options: {
    stdout: true
  }
},
```
This doesn't fail on the Firefox oddities, and produces the useful feedback I need:
```
/Users/username/Documents/path/to/project/css/file1.css: line 4585, col 3, Warning - Unknown property 'fill'.
/Users/username/Documents/path/to/project/css/file1.css: line 4586, col 3, Warning - Unknown property 'stroke'.
/Users/username/Documents/path/to/project/css/file1.css: line 4587, col 3, Warning - Unknown property 'stroke-width'.
/Users/username/Documents/path/to/project/css/file2.css: Lint Free!
/Users/username/Documents/path/to/project/css/file3.css: Lint Free!
/Users/username/Documents/path/to/project/css/file4.css: Lint Free!
/Users/username/Documents/path/to/project/css/file5.css: Lint Free!
```
