### ISSUE TITLE
Remove check for -webkit-box-sizing

### ISSUE THREAD

**Issue by AllThingsSmitty** [CSSLint/csslint#454]
The current edit comes up:

> Require compatible vendor prefixes - The property -webkit-box-sizing is compatible with -moz-box-sizing and should be included as well.

Right now `-moz-` is the only prefix needed for the box-sizing property. Can the check for `-webkit-` be removed?

**Comment by janaspage** [comment]
I don't see any vendor prefixes needed for any version of any browser when using `box-sizing`: http://caniuse.com/#search=box-sizing

**Comment by AllThingsSmitty** [comment]
@janaspage I think everyone has since caught up with `box-sizing`z
