### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by joshuaspence** [CSSLint/csslint#514]
Is it possible to have a version bump for `npm`? There are quite a few new features since v0.10.0.

**Comment by lkraav** [comment]
Bizzump. Looking for that alphabetic order rule.

**Comment by cvrebert** [comment]
@stubbornella Ping!

**Comment by jorgegc** [comment]
Hey @nschonni, what is holding this up? Please let the community know if there is anything we can do to get this out the door ASAP. Thanks!

**Comment by lukeapage** [comment]
@nschonni bump!

**Comment by bignimbus** [comment]
Bump

**Comment by Semigradsky** [comment]
The CSSLint is dead. Long live the [stylelint](https://github.com/stylelint/stylelint)!

**Comment by frvge** [comment]
@nschonni or @stubbornella , can we get a new version of parser-lib and csslint? A lot of PRs have been accepted since the project got "alive" again. Thanks.

**Comment by nschonni** [comment]
@stubbornella drop me a line if you have time. I've been a deadbeat here, and I could try to publish something, but I could just grant the NPM push to @XhmikosR and @frvge if you want.

**Comment by stubbornella** [comment]
Please do, I'm very impressed with their comtributions and excited to see csslint moving forward






On Wed, Mar 2, 2016 at 7:07 PM -0800, "Nick Schonning" <notifications@github.com> wrote:












@stubbornella drop me a line if you have time. I've been a deadbeat here, and I could try to publish something, but I could just grant the NPM push to @XhmikosR and @frvge if you want.

**Comment by nschonni** [comment]
Can you provide your NPM user names @XhmikosR and @frvge ? I tried your GitHub names, but they didn't work.

**Comment by XhmikosR** [comment]
I use the same, it's just lowercase :) https://www.npmjs.com/~xhmikosr

For parser-lib, it's basically @cscott's contributions that moved things forward.

**Comment by frvge** [comment]
@nschonni I just signed up so please try again. I'm not a node developer (mostly working on the process for csslint) so maybe it makes more sense to give a dev the rights.

**Comment by nschonni** [comment]
@frvge no problem, i'll leave you off for now then.
@XhmikosR  and @cscott I added you to this and the parser-lib package rights

**Comment by XhmikosR** [comment]
So, I made a beta branch here to try out parser-lib beta. I haven't pushed anything on npm because I think that CSSLint might break due to the changes in parser-lib.

Can someone else try the beta branch and check the dist files differences?

**Comment by DheerendraRathor** [comment]
Are we going to see any new version of CSSlint soon? It has been 3 years since 0.10.0

**Comment by hubaloo** [comment]
It sure would be great to receive a new release!

**Comment by Ryuno-Ki** [comment]
@nschonni Congratulations to the wedding.

And *BUMP*.

@XhmikosR Am I correct assuming that there are [only five issues left](https://github.com/CSSLint/csslint/milestones/1.0.0) for v1.0.0? Do you need help finishing them?

**Comment by XhmikosR** [comment]
I'm mostly concerned about the changes in parser lib. I have made a branch
which is using the latest parser lib. If we could confirm things works
right we can move forward.

**Comment by Ryuno-Ki** [comment]
@XhmikosR Can you provide a link? I couldn't find a branch from you at https://github.com/CSSLint/parser-lib/network

**Comment by XhmikosR** [comment]
https://github.com/CSSLint/parser-lib/tree/beta

**Comment by XhmikosR** [comment]
https://github.com/CSSLint/csslint/releases/tag/v1.0.0
