### ISSUE TITLE
Add inherit as known keyword value for box-shadow

### ISSUE THREAD

**Issue by stephaniehobson** [CSSLint/csslint#547]
It's not listed in 7.1 of the spec (http://dev.w3.org/csswg/css-backgrounds/#box-shadow) but buried in 2.2 is a line saying inherit is valid for all properties on the page.

**Comment by frvge** [comment]
This was fixed in parser-lib in https://github.com/CSSLint/parser-lib/commit/0427cefc89446072513282d1a117fc28e64219f6 .
