### ISSUE TITLE
Add object-fit and object-position to known properties

### ISSUE THREAD

**Issue by KaptenJansson** [CSSLint/csslint#557]
I think it makes sense to add these to known properties.
http://dev.w3.org/csswg/css-images-3/#the-object-fit
http://dev.w3.org/csswg/css-images-3/#the-object-position 

Note that Opera has a vendor prefix while Chrome >= M32 has not.

**Comment by frvge** [comment]
Thanks for the PR in the parser-lib repo. The PR was merged in parser-lib. It probably hasn't been fixed in csslint because the last release has been a while, so I'm closing this one as duplicate of #514.
