### ISSUE TITLE
Enable ignore:start and ignore:end comments to exclude arbitrary CSS from linting

### ISSUE THREAD

**Issue by samdutton** [CSSLint/csslint#558]
Like JSHint ignore:start and ignore:end comments.

Recently needed this for unknown properties that we wanted to use.

**Comment by arsgeografica** [comment]
That would be great. I add normalize.css at the start of my LESS files and keep on getting some errors which I would like to suppress only for that.

**Comment by dmose** [comment]
For those of us who work on browsers themselves, this would be tremendously helpful.

**Comment by stubbornella** [comment]
I'm open to a PR. Is this how JSHint does it?

**Comment by arsgeografica** [comment]
I added the required functionality but can't push while on the train. There are no tests yet but I'll open a PR later today for early comments.

**Comment by dmose** [comment]
@stubbornella Yes, http://jshint.com/blog/new-in-jshint-oct-2013/ is the blog post introducing that feature.

**Comment by simbo** [comment]
Ignore comments would be a great feature.

Any chance this gets merged soon?

**Comment by rodriguezmanu** [comment]
+1

**Comment by adamkudrna** [comment]
+1!

**Comment by Sciscitator** [comment]
+1

**Comment by Keysox** [comment]
+1

**Comment by Jamie452** [comment]
+1

**Comment by yppeaxy** [comment]
+1

**Comment by selkhateeb** [comment]
+1
