### ISSUE TITLE
update parserlib to 2.5?

### ISSUE THREAD

**Issue by ArgTang** [CSSLint/csslint#563]
from package.json
"dependencies": {
    "clone": "~0.1.11",
    "parserlib": "~0.2.4"
  },

https://github.com/CSSLint/parser-lib/releases

**Comment by ntwb** [comment]
This was updated to parser-lib v0.2.5 via https://github.com/CSSLint/csslint/commit/dbe5273b101cd7b35f016c096a746907e1f567ac
