### ISSUE TITLE
Remove rule for alpha order

### ISSUE THREAD

**Issue by AllThingsSmitty** [CSSLint/csslint#566]
The rule for properties to be in alpha order seems unnecessary if the dev follows a different set of standards for ordering (ex.: tools like CSSComb). This might be better suited as a toggle for those who want to follow that standard and not an actual rule that needs to be adhered to by devs.

![csslintproblems](https://cloud.githubusercontent.com/assets/1682367/5787464/8c46257e-9dce-11e4-9b3c-36dce3aec1e4.png)

**Comment by tsmiley3** [comment]
I am in the very very early stages of learning on Android.  All the crazy coding errors and out of place color stuff you see are mistakes  that  I haven't figured out how to fix.  All this so overwhelming.  I need all the help I can get. Thank you so much. From Terri Smiley

--- Original Message ---

**Comment by stubbornella** [comment]
I don't alpha order my properties either, that said, you can turn off this rule if you don't use it. If your ide doesn't let you, you can file a bug against the ide itself.
