### ISSUE TITLE
clip-path is an unknown property

### ISSUE THREAD

**Issue by MiniXC** [CSSLint/csslint#572]
The [clip-path property](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path) still causes the *unknown property* warning intended for typos to show up, although its a [Candidate Recommendation](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path#Specifications).

**Comment by frvge** [comment]
This was a parser-lib problem, but has been fixed in https://github.com/CSSLint/parser-lib/commit/e20fd7e1d7a21358868fe0a89d781107617e433b .
