### ISSUE TITLE
css length values vmin and vmax are not supported

### ISSUE THREAD

**Issue by hounshell** [CSSLint/csslint#583]
Not sure where all this should be added, or I'd do it myself, but vmin and vmax should be parsed similarly to vh and vw.

**Comment by madr** [comment]
I believe this is part of parser-lib still. 
https://github.com/csslint/parser-lib

**Comment by frvge** [comment]
This was added to parser-lib in commit https://github.com/CSSLint/parser-lib/commit/5d95ac75a9862eb54c1d3c8520f3cc09e3937f19 .
