### ISSUE TITLE
Rule proposal: disallow elements

### ISSUE THREAD

**Issue by lukasoppermann** [CSSLint/csslint#588]
I think it would be helpful to add a rule to check if elemens / tags, such as `div` are styled. The only good place to have them in your css is in a reset / normalizer. 

Especially if this https://github.com/CSSLint/csslint/issues/558 gets merged, a rule like this could help avoiding trouble with unexpected behaviour for e.g. when refactoring legacy code.

**Comment by tgfjt** [comment]
+1

**Comment by chickpeas** [comment]
+1
