### ISSUE TITLE
Missing color keyword “currentColor” leads to incorrect warning

### ISSUE THREAD

**Issue by gouch** [CSSLint/csslint#590]
![warning](https://cloud.githubusercontent.com/assets/38445/7257149/76eccc3a-e821-11e4-8347-e2a6a904666b.png)

currentColor is a valid `<color>` value, so this warning is incorrect

References: 
- http://www.w3.org/TR/css3-color/#currentcolor
- https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#currentColor_keyword

**Comment by gouch** [comment]
It looks like this might depend on parser-lib, so I created a [pull request](https://github.com/CSSLint/parser-lib/pull/153) there

**Comment by frvge** [comment]
This issue has been fixed in the parser-lib.
