### ISSUE TITLE
What about tagging a new release?

### ISSUE THREAD

**Issue by robertfausk** [CSSLint/csslint#592]
There are very many new commits since last release in August 2013.

**Comment by lorenz068** [comment]
True that!

**Comment by jawshooah** [comment]
Or perhaps put out a request for more collaborators? I realize that @nschonni and @stubbornella probably have a lot on their plates, so adding a collaborator or two to the repo would be a huge help in keeping things updated.

**Comment by cvrebert** [comment]
Duplicate of #514.

**Comment by frvge** [comment]
Closing because of duplicate. We will see about a new release soon. CC: @XhmikosR

**Comment by XhmikosR** [comment]
@frvge: I don't have npm push rights, so we'll need @stubbornella or @nschonni to do this for us.
