### ISSUE TITLE
Dead Link in Docs Page /Disallow-selectors-that-look-like-regular-expressions

### ISSUE THREAD

**Issue by whroman** [CSSLint/csslint#596]
The link at the bottom of the following page is dead.
https://github.com/CSSLint/csslint/wiki/Disallow-selectors-that-look-like-regular-expressions

Following is the URL of the dead link.
https://css-tricks.com/5591-attribute-selectors/

**Comment by ovanderzee** [comment]
They have friendly url's now. The link is now:
https://css-tricks.com/attribute-selectors/

**Comment by frvge** [comment]
Fixed.
