### ISSUE TITLE
JSON Formatter

### ISSUE THREAD

**Issue by GordonDiggs** [CSSLint/csslint#602]
Opening this issue just to see if there is interest in this. I am happy to build it if there is:

It would be great to have a JSON formatter that outputs the result of the linting in one JSON document, rather than the XML or text formatters that are present.

**Comment by jawshooah** [comment]
Absolutely! Though with the current pace of development and releases, I doubt such a feature would make it into production any time soon :cry:

**Comment by steelbrain** [comment]
Bump! It's 2015, XML is long gone, Just support JSON already! :rose:

**Comment by Arcanemagus** [comment]
An implementation of this is up in https://github.com/CSSLint/csslint/pull/606, now we just need to wait for it to get merged :wink:.

**Comment by sils1297** [comment]
Hi, we have a tool named `coala` that unifies a lot of other tools, including CSSLint and provides you with various output formats including JSON. It's free software, more info on http://coala-analyzer.org/ .

With that you can get CSSLint JSON output right now, assuming you have csslint installed on your machine:

```
pip3 install coala
coala-json --files=\*\*/\*.css --bears=CSSLintBear --save
```

The save flag will generate a coala configuration file so next time you just type `coala` or `coala-json` or whatever you want/need.

(Note: the intention behind this tool is to make the lifes of the people writing static code analysis easier so we do user interaction for them. Goal is to reduce redundancy not create some so we're currently wrapping lots of other tools so you can seamlessly use everything via coala.)

**Comment by Arcanemagus** [comment]
@sils1297 #606 was written specifically so we _don't_ need to rely on aggregator tools like that (and even more specifically so we don't have to bother with pulling in a library to parse XML...).

Our use case is the [linter-csslint](https://github.com/AtomLinter/linter-csslint) plugin for the Atom text editor, which is quite specifically for `csslint`.

That being said, that's an interesting tool and it would be nice to see it as a service provider for the [linter](https://github.com/atom-community/linter/) pacakge :wink:. If you were interested in putting that together and had any questions feel free to hop into the #linter-plugin-dev channel on [Atom's Slack](http://atom-slack.herokuapp.com/) instance.

**Comment by sils1297** [comment]
@Arcanemagus you speak of an atom linter based on the atom linter thing? Like https://github.com/coala-analyzer/coala-atom ?

**Comment by Arcanemagus** [comment]
Ha! Exactly :wink:

**Comment by frvge** [comment]
#606 has been merged. Closing this issue.
