### ISSUE TITLE
disable overqualified rule when normalizing elements

### ISSUE THREAD

**Issue by yomed** [CSSLint/csslint#610]
I have a class on a heading like this `<h1 class="heading">heading</h1>`

And css that styles the heading while also normalizing the h1:
```
h1.heading {
    font-style: italic;
    font-size: 18px;
    font-weight: normal;
    margin: 0;
}
```

In this case I need to put overqualify the selector in order to override the h1 defaults for margin and font-weight. I get the error `Element (h1.heading) is overqualified, just use .heading without element name.` I'd prefer not to disable the rule entirely, but it would be useful if it could recognize normalization before making these warnings.

**Comment by himedlooff** [comment]
The class `.heading` _will_ override the `h1` defaults. There's no need to have `h1` in your selector.

**Comment by yomed** [comment]
@himedlooff Yep you're right, I think the example got messed up when I was trying to simplify the code to post an issue... Thanks!
