### ISSUE TITLE
Why is initial not a valid value?

### ISSUE THREAD

**Issue by himedlooff** [CSSLint/csslint#618]
I'm getting the following warnings:

> Expected (<color> | inherit) but found 'initial'.
> Expected (normal | bold | bolder | lighter | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900 | inherit) but found 'initial'.

According to MDN:
> The initial CSS keyword ... is allowed on every CSS property...

https://developer.mozilla.org/en-US/docs/Web/CSS/initial

**Comment by alexpelan** [comment]
+1

**Comment by Digi59404** [comment]
You can bypass this warning by using the following at the top of your file.

/*csslint known-properties:false */

**Comment by kkirsche** [comment]
Thanks for the feedback! This would actually go in [CSSLint's parser library](https://github.com/CSSLint/parser-lib). I've created the CSSLint/parser-lib#172 there to track this.
