### ISSUE TITLE
Quiet mode has no effect using CLI

### ISSUE THREAD

**Issue by michaelalhilly** [CSSLint/csslint#624]
After reviewing the binary it seems the (--quiet) flag is not implemented in the CLI command. The argument is still defined at the top of the file but I'm not seeing it used anywhere in script. As a result setting the flag has no effect. All warnings are still outputting.

**Comment by stefan-wiesner** [comment]
I'm expieriencing thesame. Using it in CI always results in a failed build

**Comment by Shirkit** [comment]
I can confirm this issue. It's rather annoying to see warning about things I specifically set in my files.

**Comment by michaelalhilly** [comment]
Closing old question.
