### ISSUE TITLE
Use with SCSS

### ISSUE THREAD

**Issue by davidbarratt** [CSSLint/csslint#625]
Is it possible to use this library with SCSS?

**Comment by jawshooah** [comment]
Doubtful. You probably want [scss-lint](https://github.com/brigade/scss-lint) or [sass-lint](https://github.com/sasstools/sass-lint).

**Comment by davidbarratt** [comment]
@jawshooah,

Thanks, do you know if there is a way to convert a `.csslintrc` config file?
https://github.com/drupal/drupal/blob/8.0.x/.csslintrc

**Comment by jawshooah** [comment]
Not that I know of. But both projects have great configuration documentation, so you should be able to find equivalents for everything there.

**Comment by davidbarratt** [comment]
Thanks!
