### ISSUE TITLE
Allow setting indentation

### ISSUE THREAD

**Issue by sils1297** [CSSLint/csslint#626]
Would be nice to be able to set indentation to 2/4 spaces or even to use tabs.

**Comment by marcobiedermann** [comment]
@sils1297 There is a tool called [CSSComb](http://csscomb.com/) which is responsible for code format

**Comment by sils1297** [comment]
ah thanks csslint doesn't care about indentation it seems :) cool

**Comment by kevincolten** [comment]
http://stylelint.io/ supports [indentation checking](http://stylelint.io/user-guide/rules/indentation/)
