### ISSUE TITLE
SVG properties come up as unknown

### ISSUE THREAD

**Issue by apank** [CSSLint/csslint#641]
![unknown](https://cloud.githubusercontent.com/assets/6688699/13298830/660e09b4-db06-11e5-8713-d634d6f6e202.jpg)

**Comment by frvge** [comment]
This should be fixed once we update csslint to the latest parser-lib. See https://github.com/CSSLint/parser-lib/commit/30b3261566d86bbcee33d993a880dbd3ab3fbad0 . 

#514 .
