### ISSUE TITLE
Disable warnings for SVG styles and flexbox

### ISSUE THREAD

**Issue by cassidoo** [CSSLint/csslint#652]
Both SVG `fill` and `flexbox` were fixed at the parser level:
https://github.com/CSSLint/parser-lib/pull/150
https://github.com/CSSLint/parser-lib/commit/7734addd0bb52ecf4f9e871a193b08853b829445

But they still have errors in CSSLint + csslint.net.

**Comment by frvge** [comment]
This will be fixed when we have new release of parserlib and csslint and csslint.net are updated.

Duplicates #514 .
