### ISSUE TITLE
Suppress Browser Hacks

### ISSUE THREAD

**Issue by bingalls** [CSSLint/csslint#656]
As a user, I'd like clean reports on my best-effort CSS, even if it requires hacks to detect browsers & versions.
Please include an option to suppress warnings for known hacks, as defined by http://browserhacks.com/
Otherwise, you should document alternative solutions to make these hacks unnecessary.

**Comment by frvge** [comment]
Hi @bingalls , you can ignore rules per line. https://github.com/CSSLint/csslint/wiki/Ignoring-parts-of-CSS-during-linting . You should also be able to select the testcases that you'd like to run, as per the website.

For the ignoring, you need to have use the version that's in master.

**Comment by nschonni** [comment]
Closing since the latest release includes this
