### ISSUE TITLE
Error messages should include rule ID

### ISSUE THREAD

**Issue by bingalls** [CSSLint/csslint#657]
As a user, I want to know what rule caused the warning I see from CssLint.
I can then read more about the rule, or know what rule to suppress.
Currently, each warning is unclear about its source

**Comment by frvge** [comment]
Hi @bingalls . I think this was fixed in https://github.com/CSSLint/csslint/commit/ba7c0eea2d20ed89f05f92e703b54097de7601d4 .

**Comment by aprohl5** [comment]
@frvge It seems you are correct. Let's get this puppy closed out!
