### ISSUE TITLE
Git tag current versions

### ISSUE THREAD

**Issue by Ryuno-Ki** [CSSLint/csslint#658]
The [most recent git tag](https://github.com/CSSLint/csslint/tree/v0.10.0) dates 15th August 2013.

Since then, many new features (esp. csslint ignore blocks) were added, but couldn't pulled in task runners like gulp-csslint because of missing git tag.

**Comment by Arcanemagus** [comment]
The most recent git tag is also the most recent release... there just hasn't been a new version of this since then.

This is a duplicate of #514 (Which is itself 2 years old...).

**Comment by Ryuno-Ki** [comment]
Okay, Let's continue there.
