### ISSUE TITLE
'allow' directive does not seem to work (0.10.0)

### ISSUE THREAD

**Issue by lhoff** [CSSLint/csslint#665]
We have a (necessarily) empty rule in our CSS file:

`.qtyFld, .amtFld, .overUnderFld, .hasDatePicker, .valid, 
.ui-datepicker-trigger, .toggled-checkbox {
  /* used for selecting, not for styling. */ }`

Removing this rule will have adverse effects in the project, so it has to remain. However, attempts to allow the rule do not change the behavior of the linter. When the 'allow' directive is added, per the following,

`.qtyFld, .amtFld, .overUnderFld, .hasDatePicker, .valid, 
.ui-datepicker-trigger, .toggled-checkbox { /* csslint allow: empty-rules */
  /* used for selecting, not for styling. */ }`

The report still contains an empty -rules warning:
`myFile.css
1: warning at line 190, col 1
Rule is empty.
.qtyFld, .amtFld, .overUnderFld, .hasDatePicker, .valid,`

Running 0.10.0. Any thoughts?

**Comment by frvge** [comment]
Hi, please update to 1.0.0. A lot of bug fixes and features went into that.
