### ISSUE TITLE
CSSLint + Stylelint (checking rules)

### ISSUE THREAD

**Issue by alanev** [CSSLint/csslint#669]
CSSLint rule: [`universal-selector`](https://github.com/CSSLint/csslint/wiki/Disallow-universal-selector)
Type: `y`
Stylelint rule: [`selector-no-universal: true`](https://github.com/stylelint/stylelint/blob/master/src/rules/selector-no-universal/README.md)
***
CSSLint rule: [`unqualified-attributes`](https://github.com/CSSLint/csslint/wiki/Disallow-unqualified-attribute-selectors)
Type: `n`
There is no rule in stylelint that analyze attribute selectors. There is rule [`selector-no-attribute`](https://github.com/stylelint/stylelint/blob/master/src/rules/selector-no-attribute/README.md), but it disallow all selectors with attribute.
***
CSSLint rule: [`zero-units`](https://github.com/CSSLint/csslint/wiki/Disallow-units-for-zero-values)
Type: `y`
Stylelint rule: [`length-zero-no-unit: true`](https://github.com/stylelint/stylelint/blob/master/src/rules/length-zero-no-unit/README.md)
***
CSSLint rule: [`overqualified-elements`](https://github.com/CSSLint/csslint/wiki/Disallow-overqualified-elements)
Type: `x`
Stylelint rule: [`selector-no-qualifying-type`](https://github.com/stylelint/stylelint/blob/master/src/rules/selector-no-qualifying-type/README.md)
Stylelint  disallows all qualifying selectors. CSSLint allows qualifying selectors if elements are different. The difference is not big.
***
CSSLint rule: [`shorthand`](https://github.com/CSSLint/csslint/wiki/Require-shorthand-properties)
Type: `n`
***
CSSLint rule: [`duplicate-background-images`](https://github.com/CSSLint/csslint/wiki/Disallow-duplicate-background-images)
Type: `n`
There is no rules in styleslint that analyze urls at all.

**Comment by ai** [comment]
@alanev why you created spearated issue? :) post it to previous one.

**Comment by alanev** [comment]
No problem
