### ISSUE TITLE
Create CSSLint to styleling migration guide

### ISSUE THREAD

**Issue by ideadapt** [CSSLint/csslint#671]
Because of https://github.com/CSSLint/csslint/issues/668 I think its best to have a document that explains end users how to migrate. I started with a markdown sketch. Maybe we can create a wiki page based on it, so that we can continuously update it while the implementation is in progress.

What do you think?

Here it goes:

---

# Migrating from CSSLint to stylelint
This page summarizes the outcome of the [initiative to consolidate CSSLint and stylelint](https://github.com/CSSLint/csslint/issues/668).

## CSSLint rules ported to stylelint

| CSSLint | stylelint | changes |
|---|---|---|
| known-properties | property-no-unknown | added checkPrefixed option stylelint/styleling#1760 |
| disallow-duplicate-properties | declaration-block-no-duplicate-properties | added ignore: ["consecutive-duplicates-with-different-values"] stylelint/styleling#1759 |

## CSSLint rules not available in stylelint

* [outline-none](https://github.com/CSSLint/csslint/wiki/Disallow-outline%3Anone) (see [issue 1758]( https://github.com/stylelint/stylelint/issues/1758))
* https://github.com/CSSLint/csslint/wiki/Require-standard-property-with-vendor-prefix
* https://github.com/CSSLint/csslint/wiki/Don%27t-use-too-many-web-fonts
* https://github.com/CSSLint/csslint/wiki/Disallow-unqualified-attribute-selectors
* https://github.com/CSSLint/csslint/wiki/Disallow-overqualified-elements
* ... list not complete yet!

If any of the above rules should be available in stylelint, they require to be provided via plugin. As of now, there is no such plugin. See [issue 668](https://github.com/CSSLint/csslint/issues/668) for an progress on this subject.

**Comment by nschonni** [comment]
There still hasn't been any consensus that the merge is actually going to happen in the other thread, but you can always do this in the Stylelint repo  to help people that want to convert
