### ISSUE TITLE
Make npm usable with webapp

### ISSUE THREAD

**Issue by orionlee** [CSSLint/csslint#673]
For csslint's [npm package ](https://www.npmjs.com/package/csslint),  could it include core (i.e., dist/csslint.js) as well?

Use case: In my webapp, I use npm to bring in dependent libraries, so that I can include them in following manner:
```
  <script type="text/javascript" src="node_modules/csslint/dist/csslint.js"></script>
```

However, csslint npm does not provide the dist/csslint.js. Could it be included? Thanks.

**Comment by XhmikosR** [comment]
I don't see any downside.

Please make a PR by changing https://github.com/CSSLint/csslint/blob/master/package.json#L44 to `dist/` and CC me.

**Comment by mkarajohn** [comment]
@XhmikosR When can we expect an update to the `npm` package? As the moment of writing this, the `csslint.js` file is still missing in a fresh installation.

**Comment by XhmikosR** [comment]
@mkarajohn: done.
