### ISSUE TITLE
Detect missing files

### ISSUE THREAD

**Issue by szepeviktor** [CSSLint/csslint#683]
Would it be possible to detect `url()` and `@import` non-existent files with relative path?

**Comment by frvge** [comment]
@szepeviktor , no. There's no information on that given to csslint from parser-lib. Maybe a crawler-bot can help you find 404s.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
Is there a way to list urls and path in `url()`-s and `@import`-s?

**Comment by frvge** [comment]
@szepeviktor , Parserlib apparently does gives some info, for example for @import , see https://github.com/CSSLint/parser-lib/blob/master/src/css/Parser.js#L286 . You should be able to create a rule that then subsequently does a curl to check if the URL exists.

**Comment by szepeviktor** [comment]
Thank you.
