### ISSUE TITLE
Please update the documentation about configuration files

### ISSUE THREAD

**Issue by ebednarz** [CSSLint/csslint#689]
The [configuration file documentation](https://github.com/CSSLint/csslint/wiki/Command-line-interface#configuration-files) prose gives the impression that options **must** be in CLI argument format but links to an old repository of mine with a sample `.csslintrc` in JSON format. 

Parsing JSON is [implemented](https://github.com/CSSLint/csslint/blob/master/src/cli/common.js#L314l) as long as I can remember, this results in unnecessary issues.

See for example
- [CSSLint/csslint/issues/676](https://github.com/CSSLint/csslint/issues/676)
- [CSSLint/csslint/issues/643](https://github.com/CSSLint/csslint/issues/643)
- [ebednarz/csslintrc/issues/3](https://github.com/ebednarz/csslintrc/issues/3)
- [ebednarz/csslintrc/issues/1](https://github.com/ebednarz/csslintrc/issues/1)

**Comment by ebednarz** [comment]
Cf. https://github.com/CSSLint/csslint/issues/359#ref-commit-f0b4097

**Comment by frvge** [comment]
@ebednarz , would it be possible for you to move your example in a PR to csslint? You probably want to merge the open PR in your repo first.

**Comment by ebednarz** [comment]
@frvge Sorry for dropping out, it wasn’t clear to me where I would move it in CSSLint, and then I forgot. I would be happy to transfer ownership. I also haven’t really looked at the PRs yet because I haven’t used CSSLint in years and would have to read the docs first, and frankly there are more important things that I haven’t got done either 
:-\
