### ISSUE TITLE
error installing using windows 10

### ISSUE THREAD

**Issue by navotera** [CSSLint/csslint#690]
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "csslint"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! file C:\Users\hendra\AppData\Roaming\npm-cache\csslint\1.0.5\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR!
npm ERR! ^
npm ERR! File: C:\Users\hendra\AppData\Roaming\npm-cache\csslint\1.0.5\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\hendra\npm-debug.log

**Comment by frvge** [comment]
I can't reproduce this. JSON Lint is saying it's OK, and I just tried installing it via both Windows (via Node.JS command prompt) and Bash (Ubuntu Bash on Windows) which worked fine.

Can you try cleaning the npm cache and trying again? `npm cache clean`
