### ISSUE TITLE
Support for CSS Grid's new unit fr?

### ISSUE THREAD

**Issue by bjoernwibben** [CSSLint/csslint#691]
Hi there,

playing around with the new CSS Grid the line: 
`grid-template-columns: 1fr 1fr 1fr;`
gives the following error:
(errors) Unexpected token '1fr' at line 1, col 26.

Any plans on supporting CSS Grid yet?

Kind regards,

Björn

**Comment by frvge** [comment]
Hi @bjoernwibben , this is something that parser-lib should provide. I've created an issue there.

**Comment by AxelAndersen** [comment]
Getting this error in Visual Studio 2017:

Error	errors	(CssLint) Unexpected token '1fr' at line 37, col 36.

Has this been fixed?

**Comment by Jeremy-Knudsen** [comment]
Getting this error today. Doesn't seem to be fixed.

**Comment by bartb56** [comment]
Still getting this error.

**Comment by easternwawoman** [comment]
Getting error today (9/2018)

**Comment by Rey-Wang** [comment]
Getting error today (3/2019)

**Comment by jxt-martin** [comment]
Getting error in version 1.0.5 (7/2019)
