### ISSUE TITLE
Missing color

### ISSUE THREAD

**Issue by WraithKenny** [CSSLint/csslint#717]
The CSS color `rebeccapurple` is missing.

**Comment by toptalo** [comment]
This color is not described in current specification: [CSS Color Module Level 3](https://www.w3.org/TR/css3-color/#svg-color) [Recommendation]
This color is from future: [CSS Color Module Level 4](https://drafts.csswg.org/css-color/#named-colors) [Editor’s Draft]

Did not know should we add it today or it will be better to wait while CSS Color Module Level 4 becomes at least a Working Draft.

**Comment by WraithKenny** [comment]
I don't know about adopting all of level 4 yet (8-digit hex, new functions, etc.), that'd be up to you, but I think adopting the single new color wouldn't hurt anything, as everyone else has already supported it.

**Comment by frvge** [comment]
We have to wait for the new version of parser-lib to be released, but besides that it's done thanks to @toptalo .

**Comment by WraithKenny** [comment]
I think that fixed a few other slightly off colors, but didn't add `rebeccapurple` tho.

**Comment by frvge** [comment]
I just merged @toptalo 's new PR with rebeccapurple to parser-lib. You'd have to build your own version of csslint based on parser-lib's master version if you want to use it. Unfortunately I can't do releases.
