### ISSUE TITLE
Is anyone here alive?!

### ISSUE THREAD

**Issue by toptalo** [CSSLint/csslint#719]
`WARNING: Expected (static | relative | absolute | fixed) but found '-webkit-sticky'.`
`WARNING: Expected (static | relative | absolute | fixed) but found 'sticky'.`

Please merge my PR CSSLint/parser-lib#236 and update parser-lib

**Comment by toptalo** [comment]
My PR are merged. Its time to update `parser-lib` =)

**Comment by toptalo** [comment]
Also found this warning
`WARNING: Expected ([ normal | alternate ]#) but found 'reverse'.`
But there are `([normal | reverse | alternate | alternate-reverse]#)` in current `parser-lib` 

Please update parser-lib

**Comment by toptalo** [comment]
Anybody here?

**Comment by toptalo** [comment]
UP

**Comment by toptalo** [comment]
Up!

**Comment by Arcanemagus** [comment]
I'd recommend moving to https://stylelint.io/, it's based on a modern CSS toolchain and actually has people working on it.

**Comment by toptalo** [comment]
It will be beter to give me acces rights to merge my changes and publish it

**Comment by Arcanemagus** [comment]
Oh I have no rights here to do anything (It only says `Contributor` because I got a PR merged... after a year and a half of bugging about it).

**Comment by frvge** [comment]
Unfortunately only 2 people can push new versions to npm so we're also limited in what we can do. It's in the pipeline, but we don't know when it'll happen.
