### ISSUE TITLE
Unknown property 'mix-blend-mode'

### ISSUE THREAD

**Issue by toptalo** [CSSLint/csslint#742]
The `mix-blend-mode` CSS property describes how an element's content should blend with the content of the element's direct parent and the element's background.

Docs: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode)
Specification: [Compositing and Blending Level 1](https://www.w3.org/TR/compositing-1/)[CR]
Browser support: [caniuse.com](https://caniuse.com/#feat=css-mixblendmode)

**Comment by Julix91** [comment]
yes! this has been annoying me for a while now :D

**Comment by frvge** [comment]
Has been merged. I don't have permissions to create a new build unfortunately.
